# $#<brief = chest.toml for C project. | set>
[project]
name = $#<$project.name>
family = $#<$project.family>
version = $#<$project.version>
maintainer = $#<$project.maintainer>
arch = $#<$project.arch>
vendor = $#<$project.vendor>
framework = $#<$project.framework>
OS = $#<$project.OS>
compiler = $#<$project.compiler>
